name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        #with:
        #  hugo-version: "0.76.5"

      - name: build
        #run: hugo --config=config.toml,google_analytics.toml
        run: hugo #--config=config.toml

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
